# configs/sleepless_vs_overlap.yml

cluster:
  gpus: 4
  cpu_cores: 12

workload:
  generator: sample
  params:
    seed: null
    job_profiles:
      # CPU‐heavy jobs: SleepLess will grab many cores, push CPU stage down to GPU level
      - name: cpu_heavy
        count: 50
        epochs_range: [2,3]
        batch_sizes: [64]
        batches_per_epoch: 200
        cpu_ms_range: [200,240]
        gpu_ms_range: [40,50]
        submit_rate: 1/20

      # Balanced jobs: roughly equal CPU/GPU work
      - name: balanced
        count: 50
        epochs_range: [3,4]
        batch_sizes: [128]
        batches_per_epoch: 150
        cpu_ms_range: [80,100]
        gpu_ms_range: [80,100]
        submit_rate: 1/40

      # GPU‐heavy jobs: SleepLess will back off to 1 core to avoid wasted parallelism
      - name: gpu_heavy
        count: 30
        epochs_range: [1,2]
        batch_sizes: [256]
        batches_per_epoch: 100
        cpu_ms_range: [4,6]
        gpu_ms_range: [120,150]
        submit_rate: 1/60

scheduler:
  name: fcfs
  params: {}
